#!/bin/bash
# vi: set sw=4 ts=4 ai:

# OpenShift cartridge function and constant library.
# Source this file in the top of the program

# Make sure all language settings are correct
export LANG=C

# Set the PATH
export PATH=/bin/:/usr/bin:${PATH}

# Constants
export PLANON="${OPENSHIFT_PLN_DIR}/PlanonProCenter"
export JBOSS="${PLANON}/jboss-6.1.0.Final"
export JBOSS_DEF="${JBOSS}/server/default"
export TOMCAT="${PLANON}/tomcat-7.0.47"
export TOMCATPID="${OPENSHIFT_PLN_DIR}/run/tomcat.pid"
export JBOSSPID="${OPENSHIFT_PLN_DIR}/run/jboss.pid"
#
# Needed for Tomcat, but called CATALINA
#
export CATALINA_PID="${TOMCATPID}"


if [[ x"${version:-}" != x"" ]]
then
  export DOWNLOAD_FILE_JBOSS="${version}-jboss.zip"
  export DOWNLOAD_FILE_TOMCAT="${version}-tomcat.zip"
  export DOWNLOAD_FILE_WEBDAV="${version}-webdav.zip"
  export DOWNLOAD_FILE_WEBSTART="${version}-webstart.zip"
fi
#
export DOWNLOAD_LOCATION="${PLANON_FILESERVER_URL}"


# Return date/time in standard format
now()
{
	date '+%Y-%m-%d %H:%M:%S'
}


# Display a status message
showstatus()
{	RC="${1:-1}"
	shift
	message="${*:-Unknown message}"

	[[ ${RC} == 0 ]] && STATTXT="OK " || STATTXT="ERR"
	str="$(printf -- "%s - %-3d - %s - %s\n" "$(now)" "${RC}" "${STATTXT}" "${message}")"

	printf -- "${str}\n" >&2

	if ! tty -s > /dev/null
	then
		if [[ x"${RC}" == x"0" ]]
		then
			client_result "${str}"
			printf "\n"
		else
			client_error "${str}"
			printf "\n"
		fi
	fi
}


# Get a file from the web
get()
{
	SRC="${1}"
	DST="${2}"

	wget -q --http-user=cockpit 		\
		--http-password=test1234 		\
		--output-document="${DST}" 		\
	 	"${SRC}"

	 return ${?}
}
